services:
  ai_engine:
    build: .
    container_name: pip_ai_system
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
    command: python src/data_pipeline.py
    tty: true
    stdin_open: true

  training:
    build: .
    container_name: pip_training
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m src.model_utils.model_training

  inference_engine:
    build: .
    container_name: pip_inference_engine
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m src.model_utils.inference_engine


